apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeday-demo
  labels:
    app: kubeday-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeday-demo
  template:
    metadata:
      labels:
        app: kubeday-demo
    spec:
      containers:
      - name: app
        image: ghcr.io/kubeday-japan/demo-node-app:APP_VERSION
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubeday-demo
  labels:
    app: kubeday-demo
spec:
  type: NodePort
  selector:
    app: kubeday-demo
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30001

